/**
 * Pre-generated WebP puzzle pieces bundle.
 * Provides 0ms instant serving without runtime image processing or libvips dependency.
 * Auto-generated by scripts/seed-puzzles.ts.
 */

export const EMBEDDED_PIECES: Record<
  string,
  Record<number, Record<number, string>>
> = {
  "cosmic-fox": {},
  "futuristic-city": {},
  "space-explorer": {},
  "neon-cyberpunk": {},
  "abstract-geometry": {}
};

export function getEmbeddedPieceDataUrl(
  slug: string,
  gridSize: number,
  pieceId: number,
): string | null {
  return EMBEDDED_PIECES[slug]?.[gridSize]?.[pieceId] ?? null;
}

export function getEmbeddedPieceBuffer(
  slug: string,
  gridSize: number,
  pieceId: number,
): Buffer | null {
  const dataUrl = getEmbeddedPieceDataUrl(slug, gridSize, pieceId);
  if (!dataUrl) return null;
  const base64 = dataUrl.replace(/^data:image\/webp;base64,/, "");
  return Buffer.from(base64, "base64");
}

export function getEmbeddedAllPieces(
  slug: string,
  gridSize: number,
): Record<number, string> | null {
  const pieces = EMBEDDED_PIECES[slug]?.[gridSize];
  if (!pieces) return null;
  const total = gridSize * gridSize;
  if (Object.keys(pieces).length < total) return null;
  return pieces;
}

/** Legacy 3x3 helper for backward compatibility */
export function getPieceBuffer(slug: string, pieceId: number): Buffer | null {
  return getEmbeddedPieceBuffer(slug, 3, pieceId);
}

export function getAllPiecesForSlug(slug: string): Record<number, string> | null {
  return getEmbeddedAllPieces(slug, 3);
}
